[project]
name = "lcsc-db"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "nazo6", email = "git@nazo6.dev" }
]
requires-python = ">=3.13"
dependencies = [
    "pydantic>=2.10",
    "pydantic-settings>=2.9",
    "pytest>=9.1.1",
    "requests>=2.34.2",
    "tqdm>=4.70.0",
]

[project.scripts]
lcsc-db = "lcsc_db.cli:main"

[tool.pytest.ini_options]
markers = [
    "integration: mark test as live integration test",
]

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
